# Generated by Django 5.1.2 on 2024-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_created_at_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
